config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :admirers, :messages_to, :messages_from, :image
    end
  end
  resources :microposts do 
    member {post :vote, :boo}
  end
  resources :sessions, :only=> [:new, :create, :destroy, :create_mobile]
  resources :microposts, :only=> [:destroy]
  resources :relationships, :only=> [:create, :destroy]
  resources :parser, :only=> [:create]

  match '/signup',  :to=> 'users#new'
  match '/profile',  :to=> 'users#show'
  match '/signin',  :to=> 'sessions#new'
  match '/enter',  :to=> 'sessions#create_mobile'
  match '/signout', :to=> 'sessions#destroy', :via=> :delete

  match '/posts', :to=> 'sessions#create_post'
  match '/post', :to=> 'static_pages#home_post'
  match '/home', :to=> 'static_pages#home_mobile'
  match '/login', :to=> 'static_pages#home_mobile'
  match '/contact', :to=> 'static_pages#contact'
  match '/about', :to=> 'static_pages#about'
  match '/help',  :to=> 'static_pages#help'
  match '/sis',  :to=> 'static_pages#sis'

 

  root      :to=> 'static_pages#home'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts span6">
    <%= render :partial=> 'shared/feed_item', :collection=> @feed_items %>
  </ol></br>
</br>
<div id="page">
  <%= will_paginate @feed_items %>
</div>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
    <span class="content">
        <%= link_to (image_tag feed_item.user.image_url, :size => "50x50", :id=>"feedpicture"), feed_item.user %>
    <% if feed_item.is_reply_to? %>
      <%= link_to "@#{feed_item.in_reply_to.username}", feed_item.user%>
      <%= wrap(feed_item.content.gsub(/\A^@\w+/, "")) %>
    <% else %>
      <%= wrap(feed_item.content.gsub(/\A^@\w+/, ""))%>
    <% end %>
  </span>
  <span class="timestamp">
    <%= link_to feed_item.user.username, feed_item.user%> posted
    <%= time_ago_in_words(feed_item.created_at) %> ago
    <% if feed_item.is_reply_to? %>
       to <%= feed_item.in_reply_to.username %>.
    <% end %>
  </span>
  <% if !current_user?(feed_item.user)%>
    <%= link_to "Vote", vote_micropost_path(feed_item), :method=> "post" %>
  <% end %>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, :method=> :delete,
      :data=> { :confirm=> "You sure?" },
      :title=> feed_item.content %>
  <% end %>
  <span class="timestamp">
    </br>
      Popularity: <%= feed_item.reputation_for(:votes).to_i %>
    </span>
</li>

app/views/shared/_feed_mobile.html.erb
<% if @feed_items.any? %>
  <ol class="microposts span6">
    <%= render :partial=> 'shared/feed_item', :collection=> @feed_items %>
  </ol></br>
</br>
<div id="page">
  <%= will_paginate @feed_items %>
</div>
<% end %>

app/views/shared/_home.html.erb
<body>
  <div id="alignments"> 

  <center><img src="http://i46.tinypic.com/2cmt2lx.png"/></center>
  <div id="image"><a href="#"/> <img src="http://i49.tinypic.com/1eudnc.png" class="grayscale"/></a></div>
</div>
<div id="alignment">
<div class="rows">
  <div class="span4 offset3">
    <h1><b>Kiido.ph is under Awesome maintenance will be back soon :)</b></h1>

 </div>
  </div>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
    </div>
    </body>

app/views/shared/_home_mobile.html.erb
<body id="max">
<div class="rows mgin">
<div class="span4 offset3">
    <em><b>Sign in</b></em>
  </br>
</br>
</br>
</br>
    <%= form_for(:sessions, :url=> '/enter') do |f| %>

      <%= f.label :username%>
      <%= f.text_field :username %>

      <%= f.label :password %>
      <%= f.password_field :password %>

     <alignleft> <%= f.submit "Sign in", :class=> "btn btn-large btn-primary" %>
    <% end %>
      </br>
    </br>
  </br>
 </div>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br></div>
</body>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', :object=> f.object %>
    <div class="field">
        <%= f.text_area :content, :placeholder=> "Compose new micropost..." %>
    </div>
    <%= f.submit "Post", :class=> "btn btn-large btn-primary" %>
    

<% end %>

app/views/shared/_microposts.html.erb
<table class="front" summary="For signed-in users">
  <tr>
    <td class="main">
      <h1 class="micropost">What's up?</h1>
      <%= render 'shared/micropost_form' %>
      <%= render 'shared/feed' %>
    </td>
    <td class="sidebar round">
      <%= render 'shared/user_info' %>
      <%= render 'shared/stats' %>
    </td>
  </tr>
</table>

app/views/shared/_parser_form.html.erb
<%= form_tag '/parser' do %>
  <!--%= render 'shared/error_messages', :object => f.object %-->
  <div class="field">
    <%= text_area_tag 'command', params[:command],:maxlength=> 140, :placeholder=> "Holla, holla, playa! Wazzup?" %>
  </div>
  <%= submit_tag "Post", :class=> "btn btn-large btn-primary", :name=> nil %>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_tag '/parser' do %>
  <!--%= render 'shared/error_messages', :object => f.object %-->
  <div class="field">
    <%= text_area_tag 'command', params[:command],:maxlength=> 140, :placeholder=> "Holla, holla, playa! Wazzup?" %>
  </div>
  <%= submit_tag "Post", :class=> "btn btn-large btn-primary", :name=> nil %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<center>
<div class="stats">
  <div class="stats">
  <a href="<%=user_path(@user)%>">
    <strong id="microposts" class="stat">
      <%= @user.microposts.count %>
    </strong>
    Posts
  </a>
  <a href="<%= admirers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Admirers
  </a>
</div>
</center>

app/views/shared/_stats_profile.html.erb
<% @user ||= current_user %>
<div class="statss">
  <a href="<%=user_path(@user)%>">
    <strong id="microposts" class="stat">
      <%= @user.microposts.count %>
    </strong>
    Posts
  </a> 
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    Admiring
  </a>
  <a href="<%= admirers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Admirers
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
<center>  <%=image_tag current_user.image, :size => "250x250", :id=>"profilepicture" %> </center>
<h1><center>@<%= current_user.username %></center></h1>
</a>

app/views/shared/_user_navb.html.erb
<a href="<%= user_path(current_user) %>">
	<div class="row" id="aup">
	 <g><%= image_tag current_user.image, :size => "20x20", :id=>"usernavb"%> <%=current_user.username%></g>
	</div>
	</a>