config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :admirers, :messages_to, :messages_from, :image
    end
  end
  resources :microposts do 
    member {post :vote, :boo}
  end
  resources :sessions, :only=> [:new, :create, :destroy, :create_mobile]
  resources :microposts, :only=> [:destroy]
  resources :relationships, :only=> [:create, :destroy]
  resources :parser, :only=> [:create]

  match '/signup',  :to=> 'users#new'
  match '/profile',  :to=> 'users#show'
  match '/signin',  :to=> 'sessions#new'
  match '/enter',  :to=> 'sessions#create_mobile'
  match '/signout', :to=> 'sessions#destroy', :via=> :delete

  match '/posts', :to=> 'sessions#create_post'
  match '/post', :to=> 'static_pages#home_post'
  match '/home', :to=> 'static_pages#home_mobile'
  match '/login', :to=> 'static_pages#home_mobile'
  match '/contact', :to=> 'static_pages#contact'
  match '/about', :to=> 'static_pages#about'
  match '/help',  :to=> 'static_pages#help'
  match '/sis',  :to=> 'static_pages#sis'

 

  root      :to=> 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<% if signed_in? %>
<% else %>
<footer class="footer">
  <small>
    Copyright
    <x>2013</x> <a href="http://orangeapps.weebly.com/" target="_blank"> OrangeApps</a><x>, All rights reserved.</x>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home",   root_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <!--li><%= link_to "Contact", contact_path %></li-->
      <li><a href="http://orangeapps.weebly.com/news" target="_blank">News</a></li>
    </ul>
  </nav>
</footer>
<% end %>

app/views/layouts/_header.html.erb
<% if signed_in? %>
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="navigatebar-inner">
  <div class="container">
    <nav>
      <%= link_to image_tag("icon.png", :id=> "logo"), root_path  %>
    <ul class="nav pull-right menu">

      <li><%= render 'shared/user_navb'%>
      <li><%= link_to "Home", root_path, :id=> "text" %></li>
        <li><%= link_to "Users", users_path, :id=> "text" %></li>
        <li id="msg-menu" class="dropdown">
          <a href="#" class = "dropdown-toggle" data-toggle="dropdown" style="color: #ffffff;background-color: #212121">
            Messages
          </a>
          <ul class="dropdown-menu menu">
            <li><%= link_to "Received", messages_to_user_path(current_user) %></li>
            <li><%= link_to "Sent", messages_from_user_path(current_user) %></li>
          </ul>
        <li id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff;background-color: #212121">
            Account
          </a>
          <ul class="dropdown-menu menu">
           
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li><%= link_to "Student", sis_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <li class="divider"> </li>
            <li>
            <%= link_to "Sign out", signout_path, :method=> :delete %>
            </li>
          </ul>
        </li>
    </ul>
    </nav>
  </div>
</div>
</header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head><LINK REL="SHORTCUT ICON" HREF="http://www.kiido.ph/favicon.ico">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/stylesheets/bootstrap-responsive.css" rel="stylesheet">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", :media=> "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <!--[if lt IE 9]>
    <script src="http://html5shim/googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    
    <div class="container">
      <%= render 'layouts/header' %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>